Fixed CONFIG flag, hyprpm setup and added reboot check

diff --git a/install b/install
--- a/install
+++ b/install
@@ -117,15 +117,15 @@ fi
 sleep 3
 
 # 5. Configs
-while true; do
-    read -p "Proceed with changing configs? [y/n]" configyn
-    case $configyn in
-        [Yy]* ) break;;
-        [Nn]* ) exit;; 
-        * ) echo "Input y/n.";;
-    esac
-done
 if [[ $CONFIG == 0 ]]; then
+	while true; do
+    		read -p "Proceed with changing configs? [y/n]" configyn
+    		case $configyn in
+        		[Yy]* ) break;;
+        		[Nn]* ) exit;; 
+        		* ) echo "Input y/n.";;
+    		esac
+	done
 	SUFFIX="-pre-sakoora"
 	printf "\nRenaming preexisting config files\n"
 	if [[ -d ~/.config/hypr ]]; then
@@ -146,6 +146,9 @@ if [[ $CONFIG == 0 ]]; then
 	if [[ -f ~/.config/rofi ]]; then
 		mv ~/.config/rofi ~/.config/rofi$SUFFIX
 	fi
+	if [[ -f ~/.config/scripts ]]; then
+		mv ~/.config/scripts ~/config/scripts$SUFFIX
+	fi
 	printf "\nOld config files have been renamed to [config_folder]-pre-sakoora.\n"
 	sleep 0.5
 	printf "\nMoving config files from .dotfiles to required location"
@@ -155,6 +158,7 @@ if [[ $CONFIG == 0 ]]; then
 	mv $DOTPATH/.config/kitty ~/.config/
 	mv $DOTPATH/.config/waybar ~/.config/
 	mv $DOTPATH/.config/rofi ~/.config/
+	mv $DOTPATH/.config/scripts ~/.config/
 	sleep 0.5
 	printf "\nMoving wallpapers"
 	if [[ -d ~/Pictures ]]; then
@@ -178,6 +182,7 @@ if [[ $CONFIG == 0 ]]; then
 	else
 		mv $DOTPATH/fonts ~/.local/share/
 	fi
+	sed -i 's/CONFIG="0"/CONFIG="1"/' $FLAGPATH
 else
 	printf "\nConfiguration is already completed.\n"
 fi
@@ -203,14 +208,31 @@ if [[ $APPDEF == 0 ]]; then
 else
 	printf "\nDefaults already setup.\n"
 fi
+
+printf "\nIt is recommended to reboot your system and log into hyprland (uwsm-managed) through sddm now.\n"
+while true; do
+    		read -p "Would you like to continue the installation [y/n]" rebootyn
+    		case $rebootyn in
+        		[Yy]* ) exit;;
+        		[Nn]* ) echo "You can always continue the installation where you left off by running the script again."
+				break;;
+        		* ) echo "Input y/n.";;
+    		esac
+done
+
 # 7. Hyprcursor
 if [[ $HYPRCURSOR == 0 ]]; then
 	printf "\nDynamic cursor installation requires you to be logged into a hyprland session.\n"
 	if hyprctl monitors > /dev/null 2>&1; then
 	while true; do
-    		read -p "Install dynamic cursor? [y/n]" configyn
-    		case $configyn in
-        		[Yy]* ) hyprpm add https://github.com/virtcode/hypr-dynamic-cursors
+    		read -p "Install dynamic cursor? [y/n]" cursoryn
+    		case $cursoryn in
+        		[Yy]* ) hyprpm update
+				if [[ $? -gt 0 ]]; then
+					printf "\nHyprpm setup failed. Check your internet connection and try again.\n"
+					exit
+				fi
+				hyprpm add https://github.com/virtcode/hypr-dynamic-cursors
 				hyprpm enable dynamic-cursors
 				if [[ $? -gt 0 ]]; then
 					printf "\nInstallation of dynamic cursor failed. Have you logged into hyprland?\nExiting...\n"
@@ -224,7 +246,7 @@ if [[ $HYPRCURSOR == 0 ]]; then
     		esac
 	done
 	else
-		echo "Hyprland is not running."
+		echo "Hyprland is not running. Dynamic cursor cannot be installed."
 	fi
 fi
 printf "\nReached the end of the installation!\n"
